CREATE TABLE IF NOT EXISTS Tickets (
    Ticket_ID SERIAL PRIMARY KEY,
    User_ID INT NOT NULL,
    Date_Created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Date_Paid TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (User_ID) REFERENCES Users(ID)
);
